server:
  port: 8881
spring:
  datasource:
    url: jdbc:mysql://39.108.48.29:3306/deri?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    data-password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 39.108.48.29
    port: 6379
    password: hiram
    timeout: 0