server:
  port: 8881
spring:
  datasource:
    url: jdbc:mysql://39.108.48.29:3306/hiramexpress?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'root'
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 39.108.48.29
    port: 6379
    password: hiram
    timeout: 200
logging:
  pattern:
    console: "%boldGreen(%d{yyyy-MM-dd HH:mm:ss.SSS}) %highlight(%-5level) %cyan(%-35logger{35}) - %msg %n"
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hiramexpress.domain